# Generated by Django 5.1.3 on 2024-12-01 15:01

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('idadmin', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_negocio', models.CharField(max_length=100)),
                ('direccion_negocio', models.CharField(max_length=150)),
                ('correo_negocio', models.CharField(max_length=100)),
                ('telefono_negocio', models.CharField(max_length=15)),
                ('pagina_web', models.CharField(max_length=100)),
                ('facebook_negocio', models.CharField(max_length=100)),
                ('numero_cuenta', models.CharField(max_length=50)),
                ('tipo_cuenta', models.CharField(max_length=30)),
                ('banco', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion_cliente', models.CharField(max_length=20)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('fecha_registro', models.DateField()),
                ('telefono', models.CharField(max_length=15)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo_electronico', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('idevento', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('valor_referencial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_horas_permitidas', models.IntegerField()),
                ('valor_extra_hora', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('idpromocion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_promocion', models.CharField(max_length=100)),
                ('valor_referencial_promo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_promocion', models.CharField(max_length=100)),
                ('porcentaje_promocion', models.IntegerField()),
                ('fecha_vigencia', models.DateField()),
                ('fecha_caducidad', models.DateField()),
                ('estado_promocion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('idservicio', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_servicio', models.CharField(max_length=150)),
                ('valor_unidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_servicio', models.CharField(max_length=100)),
                ('fecha_entrega', models.DateTimeField()),
                ('descripcion_unidad', models.CharField(max_length=200)),
                ('fecha_actualizacion_precio', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeEvento',
            fields=[
                ('idTipo_De_Evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(max_length=50)),
                ('url_imagen', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('fecha_creacion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('idalquiler', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_alquiler', models.DateField()),
                ('horainicio_reserva', models.TimeField()),
                ('horain_planificada_reserva', models.TimeField()),
                ('horafin_real_reserva', models.TimeField()),
                ('costo_alquiler', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calificacion_negocio', models.IntegerField()),
                ('observacion', models.TextField()),
                ('cantidad_anticipo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_de_alquiler', models.CharField(max_length=30)),
                ('idcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alquileres', to='eventos.cliente')),
                ('idevento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alquileres', to='eventos.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Eventualidad',
            fields=[
                ('ideventualidad', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_eventualidad', models.CharField(max_length=200)),
                ('fecha_eventualidad', models.DateField()),
                ('tipo_eventualidad', models.CharField(max_length=20)),
                ('costo_eventualidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('responsable', models.CharField(max_length=100)),
                ('fecha_resolucion', models.DateField(blank=True, null=True)),
                ('idalquiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventualidades', to='eventos.alquiler')),
            ],
        ),
        migrations.CreateModel(
            name='FotoAlquiler',
            fields=[
                ('idFoto_Alquiler', models.AutoField(primary_key=True, serialize=False)),
                ('url_foto', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_subida', models.DateTimeField()),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('idevento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_alquiler', to='eventos.evento')),
            ],
        ),
        migrations.CreateModel(
            name='FotoServicio',
            fields=[
                ('idfoto_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('url_imagen', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('descripcion_foto', models.TextField()),
                ('fecha_publicacion', models.DateTimeField()),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('idservicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='eventos.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='AlquilerServicio',
            fields=[
                ('idalquiler_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calificacion_cliente', models.IntegerField()),
                ('idalquiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='eventos.alquiler')),
                ('idservicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alquileres', to='eventos.servicio')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo_de_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='eventos.tipodeevento'),
        ),
    ]
