# Generated by Django 5.1.3 on 2024-12-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_alter_administrador_correo_negocio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoalquiler',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
