# Generated by Django 5.1.3 on 2024-12-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_alter_fotoalquiler_fecha_subida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoservicio',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
