# Generated by Django 5.1.3 on 2024-12-09 13:32

import eventos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_alter_cliente_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=10, validators=[eventos.validators.validar_numero_celular], verbose_name='Número de celular'),
        ),
    ]
