# Generated by Django 5.1.3 on 2024-12-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_rename_horain_planificada_reserva_alquiler_horafin_planificada_reserva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='estado_de_alquiler',
            field=models.CharField(choices=[('R', 'Reservado'), ('O', 'Ocupado'), ('F', 'Finalizado')], max_length=30),
        ),
    ]
